books/urls.py
from django.urls import path
from .views import *
from accounts.views import logout, profile

urlpatterns = [
    path('', homepage_books_display, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('howitworks/', HowItWorksView.as_view(), name='how_it_works'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('mylibrary/', get_my_books, name='mylibrary'),
    path('export_excel', get_my_books_exel_file, name='export-excel'),
    path('export/csv/', export_books_csv, name='export_books_csv'),
    path('communicate/', new_message, name='message'),
    path('communicate/<int:pk>/back', answer_message, name='answer_message'),
    path('mylibrary/<int:pk>/details', show_detail_view, name='book_details'),
    path('mylibrary/<int:pk>/edit', BookEditView.as_view(), name='book_edit'),
    path('mylibrary/<int:pk>/delete', BookDeleteView.as_view(), name='book_delete'),
    path('profile/', profile, name='profile'),
    path('mylibrary/book_register/', BookCreationView.as_view(), name='book_register'),
    path('mylibrary/book_register/success', BookUploadSuccess.as_view(), name='success_upload'),
    path('logout/', logout, name='logout'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('admin/', admin.site.urls),
      path('captcha/', include('captcha.urls')),
      path('ratings/', include('star_ratings.urls', namespace='ratings')),
      path('accounts/', include('django.contrib.auth.urls')),
      path('accounts/', include('accounts.urls')),
      path('', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.contrib.auth.models import User
from django.db import models
from accounts.models import MyUser
from django.conf import settings


class Message(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author_messages', on_delete=models.CASCADE)
    recipient = models.IntegerField()
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

    def last_15_messages(self):
        return Message.objects.order_by('-timestamp').all()[:15]


def upload_to(instance, filename):
    get_user_object = MyUser.objects.filter(email=instance.owner)
    user = get_user_object.get(email=instance.owner)

    return '{username}/{filename}'.format(username=user.username, filename=filename)


class Book(models.Model):
    GENRE_CHOICES = [
        ('biografija', 'Biografija'),
        ('gamta', 'Gamta'),
        ('grozine literatura', 'Grožinė literatūra'),
        ('humoras ir pramogos', 'Humoras & Pramogos'),
        ('inzinerija ir transportas', 'Inžinerija & Transportas'),
        ('istorija', 'Istorija'),
        ('keliones', 'Kelionės'),
        ('komiksai', 'Komiksai'),
        ('kompiuteriai ir it technologijos', 'Kompiuteriai ir IT technologijos'),
        ('kulinarija', 'Kulinarija'),
        ('medicina', 'Medicina'),
        ('menas', 'Menas'),
        ('mokslas', 'Mokslas'),
        ('moksline fantastika', 'Mokslinė fantastika'),
        ('politika ir socialiniai mokslai', 'Politika ir socialiniai mokslai'),
        ('pomegiai', 'Pomėgiai'),
        ('religija', 'Religija'),
        ('sportas ir aktyvus poilsis', 'Sportas ir aktyvus poilsis'),
        ('sveikata ir dieta', 'Sveikata ir dieta'),
        ('seima', 'Šeima'),
        ('teise', 'Teisė'),
        ('vaikams ir jaunimui', 'Vaikams ir jaunimui'),
        ('verslas', 'Verslas'),
        ('NOT_INCLUDED', 'Kita'),
    ]
    LANGUAGE_CHOICES = [
        ('LT', 'Lietuvių'),
        ('EN', 'Anglų'),
        ('PL', 'Lenkų'),
        ('RU', 'Rusų'),
        ('XX', 'Kita'),
    ]
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    summary = models.TextField(blank=True, help_text="Įveskite trumpą knygos aprašymą")
    isbn = models.PositiveBigIntegerField(null=True, blank=True)
    genre = models.CharField(max_length=255, blank=True, choices=GENRE_CHOICES)
    upload = models.ImageField(upload_to=upload_to, max_length=150,
                               blank=True, null=True, default='no_book_image.png')
    language = models.CharField(max_length=150, choices=LANGUAGE_CHOICES, default='LT')
    for_sale = models.BooleanField(help_text="Pardavimas")
    price = models.PositiveIntegerField(blank=True, null=True)
    for_exchange = models.BooleanField(help_text="Apsikeitimas")
    for_donation = models.BooleanField(help_text="Dovana")
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} | Owner: {self.owner.username}'

    @property
    def user(self):
        return User.objects.get(pk=self.user_id)

    def save(self, *args, **kwargs):
        if not self.upload:
            self.upload = 'media/no_book_image.png'
        super().save(*args, **kwargs)


class Comment(models.Model):
    commented_book = models.ForeignKey(Book, on_delete=models.CASCADE)
    commented_username = models.CharField(max_length=100)
    comment_name = models.CharField(max_length=50, help_text='Komentaro pavadinimas')
    comment_text = models.TextField(max_length=1000, help_text='Komentaro tekstas')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return 'Comment by {}'.format(self.commented_book)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About page{% endblock %}


{% block content %}
    <p>What is Lorem Ipsum?</p>
    <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a
        type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions
        of
        Lorem Ipsum.</p>

    <p> Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at
        its
        layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed
        to
        using 'Content here, content here', making it look like readable English. Many desktop publishing packages and
        web
        page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many
        web
        sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on
        purpose (injected humour and the like).</p>

    <p>Where does it come from?
        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin
        literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
        College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and
        going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum
        comes
        from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
        written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The
        first
        line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections
        1.10.32
        and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
        accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

templates/all_my_messages.html
{% extends 'base.html' %}
{% load static %}
{% block title %}All my messages{% endblock %}


    {% block content %}


    {% endblock content %}

templates/answer_message.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Answer message{% endblock %}


{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <p>"{{ sender_username.username }}" paraše: </p>
        <p><i>{{ content }}</i></p>
        <p>Atsakyti: </p>
        <form method="post">
            {% csrf_token %}
            <p>{{ form.content }}</p>
            <p><input type="submit" value="Siusti"></p>
        </form>
        <a href="{% url 'home' %}">Atgal</a>
{#        <button onclick="location.href='{% url 'home' %}'" type="button">Back</button>#}
    {% endif %}
{% endblock content %}

templates/base.html
{% load static %}
{% load ratings %}
<!DOCTYPE html>
{% load ratings %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Book Exchange Base{% endblock %}</title>
    {#================mano laikinni stiliai======================#}
    <link rel="shortcut icon" href="{% static 'media/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Arvo"/>
    {#==================================rating stiliai=================================================#}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    {#===============================mano js funkcijos=======================================#}
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    {#========================================bootstrap===================================================#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    {#===================================mano bootstrapo priedas============================================#}
    <link rel="stylesheet" href="{% static 'css/b_footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/headers.css' %}">
    <link rel="stylesheet" href="{% static 'css/after_bootstrap.css' %}">

</head>
<body class="d-flex flex-column min-vh-100 bg-light">

<header class="p-2 mb-1 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-end">
            <a href="/" class="d-flex align-items-center mb-2 ms-lg-auto mb-lg-0 text-dark text-decoration-none">
                <img class="logo" src="{% static '/media/logo.png' %}" alt="logo">&nbsp;&nbsp;<span class="fs-3">  Knygų mainai</span>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'mylibrary' %}" class="nav-link px-3 link-dark">Mano biblioteka</a></li>
                    <li><a href="{% url 'profile' %}" class="nav-link px-3 link-dark">Profilis</a></li>
                    <li><a href="{% url 'logout' %}" class="nav-link px-4 link-dark">Atsijungti</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}" class="nav-link px-4 link-dark">Prisijungti</a></li>
                    <li><a href="{% url 'register' %}" class="nav-link px-4 link-dark">Registruotis</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
<div class="">
    {% block content %}

    {% endblock content %}
</div>
<footer class="mt-auto">
    <div class="container">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-muted">&copy; 2022 VVK BD</p>

            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-muted">Apie projektą</a></li>
                <li class="nav-item"><a href="{% url 'how_it_works' %}" class="nav-link px-2 text-muted">Kaip tai
                    veikia?</a></li>
                <li class="nav-item"><a href="{% url 'feedback' %}" class="nav-link px-2 text-muted">Susisiekti</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>
<script src="{% static 'js/my_js.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script>
    window.onload = get_recipient_username;
    window.onload = set_recipient_username;
    window.onload = price_function;
    document.getElementsByClassName("star-ratings-rating-average")[0].firstChild.nodeValue = "Vidutinis: ";
    document.getElementsByClassName("star-ratings-rating-count")[0].firstChild.nodeValue = "Įvertinimų skaičius: ";
    document.getElementsByClassName("star-ratings-rating-user")[0].firstChild.nodeValue = "Jūs įvertinote: ";
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>
</html>

templates/book_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book delete{% endblock %}


{% block content %}
    <form method="post">{% csrf_token %}
        <H2>Ar esate įsitikinę, kad norite ištrinti "{{ object.title }}"?</H2>
        {{ form }}
        <input type="submit" class="my-book-delete-btn" value="Confirm">
    </form>

{% endblock content %}

templates/book_details.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% block title %}Book details{% endblock %}


{% block content %}
    <div>
        <h3>{{ book.title }}</h3><br>
        <h5>{{ book.author }}</h5><br>
        <p>{{ book.summary }}</p><br>
    </div>
    <div>

        <p>{{ book.isbn }}</p><br>
        <p>{{ book.get_genre_display }}</p><br>
        <p>{{ book.language }}</p><br>
        {% if user.is_authenticated %}
            {% if user_owner.username != user.username %}
                <p>Knygos savininkas: <span id="recipient-username">{{ user_owner.username }}</span>
                    &nbsp;&nbsp;&nbsp;<a href="{% url 'message' %}"> Parašyti savininkui</a></p><br>

                {% ratings book.owner %}
            {% else %}
                <p>Jūsu knyga įkelta {{ book.publish }}</p>
            {% endif %}
        {% endif %}
    </div>
    <div class="card shadow-sm my-book-div-width">
        <div class="">
            <img class="bd-placeholder-img card-img-top my-img-size"
                 width="100%" height="225"
                 src="{{ book.upload.url }}"
                 alt="{{ book.title }}">
            </a>
        </div>
        <div>
            {% if user_owner.username == user.username %}
                <p>
                    <a href="{% url 'book_edit' book.id %}">Redaguoti</a> |
                    <a href="{% url 'book_delete' book.id %}">Ištrinti</a>
                </p>
            {% endif %}

        </div>
    </div>
    <div class="card-body">
        <h3>Palikti komentarą</h3>
        <form method="post">
            {% csrf_token %}
            <p>Komentaro pavadinimas{{ comment_form.comment_name }}</p>
            <p>Komentaro tekstas{{ comment_form.comment_text }}</p>
            <button type="submit" class="btn btn-primary  btn-lg">Pateikti</button>
        </form>
    </div>
    <br>
    <br>
    <div>
        {% for comment in all_this_book_comments %}
            <div style="border: solid darkblue 1px">
                <p>Komentatorius: {{ comment.commented_username }}</p>
                <p>Pavadinimas: {{ comment.comment_name }}</p>
                <p>Tekstas: {{ comment.comment_text }}</p>
                <p>Data, laikas: {{ comment.created }}</p>
            </div><br>
        {% endfor %}
    </div>

{% endblock content %}

templates/book_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book edit{% endblock %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary  btn-lg">Išsaugoti</button>
    </form>

{% endblock content %}

templates/book_register.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="my-book-reg">
        <div class="my-book-register-conteiner">
            {% if user.is_superuser or user.is_authenticated %}
                <form enctype="multipart/form-data" method="POST" class="my-auth-form" action=''>
                    <div class="my-form-container">
                        {% csrf_token %}
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_title">Knygos pavadinimas</label>
                            </div>
                            <div class="col-right">
                                {{ form.title }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_author">Autorius</label>
                            </div>
                            <div class="col-right">
                                {{ form.author }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_summary">Santrauka</label>
                            </div>
                            <div class="col-right">
                                {{ form.summary }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_isbn">ISBN</label>
                            </div>
                            <div class="col-right">
                                {{ form.isbn }}
                                <p id="my-mes-summary"></p>
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_genre">Žanras</label>
                            </div>
                            <div class="col-right">
                                {{ form.genre }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_upload">Viršelio nuotrauka</label>
                            </div>
                            <div class="col-right">
                                {{ form.upload }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_language">Kalba</label>
                            </div>
                            <div class="col-right">
                                {{ form.language }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_for_sale">Parduodama</label>
                            </div>
                            <div class="col-right">
                                {{ form.for_sale }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_price">Kaina</label>
                            </div>
                            <div class="col-right">
                                {{ form.price }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_for_exchange">Mainams</label>
                            </div>
                            <div class="col-right">
                                {{ form.for_exchange }}
                            </div>
                        </div>
                        <div class="my-book-reg-row">
                            <div class="col-left">
                                <label class="my-book-reg-label" for="id_for_donation">Dovana</label>
                            </div>
                            <div class="col-right">
                                {{ form.for_donation }}
                            </div>
                        </div>
                        <button type="submit" class="my-form-submit-btn">Pridėti</button>
                    </div>
                </form>
                <a class="my-forml-back-link" href="{% url 'home' %}">Atgal</a>
            {% endif %}
        </div>
    </div>
    <br>
    <br>

{% endblock content %}

templates/book_upload_success.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1>Sėkmingas knygos įkėlimas</h1>

    <a href="{% url 'mylibrary' %}">Sugrįžti</a>



{% endblock content %}

templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Feedback page{% endblock %}


{% block content %}
    <p>What is Lorem Ipsum?</p>
    <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a
        type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions
        of
        Lorem Ipsum.</p>

    <p> Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at
        its
        layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed
        to
        using 'Content here, content here', making it look like readable English. Many desktop publishing packages and
        web
        page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many
        web
        sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on
        purpose (injected humour and the like).</p>

    <p>Where does it come from?
        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin
        literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
        College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and
        going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum
        comes
        from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,
        written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The
        first
        line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections
        1.10.32
        and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
        accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="my-search-container">
        <form name="" action="" method="get">
            <div class="col-md-4 mx-auto">
                <div class="input-group ">
                    <label for="example-search-input"></label>
                    <input name="q" class="form-control" type="search"
                           placeholder="ieškoti pagal pavadinimą, autorių, žanrą, ISBN"
                           id="example-search-input">
                </div>
            </div>
        </form>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="album py-5">
        <div class="">
            <div class="row  g-3 my-lib">
                {% for book in data %}
                    <div class="col">
                        <div class="card shadow-sm my-book-div-width">
                            <div class="">
                                <a href="{% url 'book_details' book.pk %}">
                                    <img class="bd-placeholder-img card-img-top my-img-size"
                                         width="100%" height="225"
                                         src="{{ book.upload.url }}"
                                         alt="{{ book.title }}">
                                </a>
                            </div>
                            <div class="card-body">
                                <p class="card-text my-text-align">{{ book.title }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

{% endblock content %}

templates/how_it_works.html
{% extends 'base.html' %}
{% load static %}
{% block title %}How It Works page{% endblock %}


{% block content %}
    <p>What is Lorem Ipsum?</p>
    <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a
        type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions
        of
        Lorem Ipsum.</p>

    <p> Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at
        its
        layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed
        to
        using 'Content here, content here', making it look like readable English. Many desktop publishing packages and
        web
        page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many
        web
        sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on
        purpose (injected humour and the like).</p>



{% endblock content %}

templates/mylibrary.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="my-library-add-block">
        <input class="btn-grad" type="button" value="Pridėti knygą" onclick="location.href='{% url 'book_register' %}'">
    </div>
    <div class="album py-5">
        <div class="">
            <div class="row  g-3 my-lib">
                {% for book in data %}
                    <div class="col">
                        <div class="card shadow-sm my-book-div-width">
                            <div class="">
                                <a href="{% url 'book_details' book.pk %}">
                                    <img class="bd-placeholder-img card-img-top my-img-size"
                                         width="100%" height="225"
                                         src="{{ book.upload.url }}"
                                         alt="{{ book.title }}">
                                </a>
                            </div>
                            <div class="card-body">
                                <p class="card-text my-text-align">{{ book.title }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/new_message.html
{% extends 'base.html' %}
{% load static %}
{% block title %}New message{% endblock %}


{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if user.is_authenticated %}
        <h4>Parašyti knygos savininkui</h4>

        <form method="post">
            {% csrf_token %}
            <p>{{ form.content }}</p>
            <p><input type="submit" value="Siusti"></p>
        </form>
        <a href="{% url 'home' %}">Atgal</a>
        {#        <button onclick="location.href='{% url 'home' %}'" type="button">Back</button>#}
    {% endif %}



{% endblock content %}